FROM centos:centos7.3.1611

RUN yum update -y && yum install -y \
    bc \
    curl-devel \
    epel-release \
    expat-devel \
    fontconfig.x86_64 \
    freetype.x86_64 \
    gettext-devel \
    git \
    libpng.x86_64 \
    libpng12.x86_64 \
    libSM.x86_64 \
    libstdc++.x86_64 \
    libXrender.x86_64 \
    libXext.x86_64 \
    openssl-devel \
    perl-ExtUtils-MakeMaker \
    tar \
    unzip \
    wget \
    zlib-devel

RUN rpm --rebuilddb ; \
    yum clean all && yum install -y \
    numpy.x86_64

# Permit access to fsl installation script (must exist locally)
# ADD ./myFslInstallerScript.sh /myFslInstallerScript.sh
# https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-6.0.4-sources.tar.gz 

RUN yum install -y which file mesa-libGL-devel 
RUN cd /tmp/ &&\
    wget https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-5.0.10-centos6_64.tar.gz -O fsl-5.0.10.tar &&\
    tar xf fsl-5.0.10.tar -C /usr/local/src
    # echo -e "/usr/local/src/fsl" | python fslinstaller.py

# Install fsl to default dir
# RUN echo -e "/usr/local/src" | ./myFslInstallerScript.sh 5.0.6 CentOS5 /usr/local/src /usr/local/etc/

# Set environment variables (run export not needed)
ENV FSLDIR=/usr/local/src/fsl \
    FSLOUTPUTTYPE=NIFTI_GZ \
    FSLGECUDAQ=cuda.q
#    CARET7DIR=/usr/local/src/tools/workbench/
ENV PATH=${FSLDIR}/bin:${PATH} \
    FSLTCLSH=${FSLDIR}/bin/fsltclsh \
    FSLWISH=${FSLDIR}/bin/fslwish
ENV HOME=/usr/local/src

RUN yum install -y python-pip vim
# FSL analysis requirement
COPY BIDSto3col.sh /bin/
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
ENV USER 1000


# Install Verificarlo
RUN yum group install "Development Tools" -y &&\
    yum install -y python3 python3-devel centos-release-scl &&\
    yum-config-manager --enable rhel-server-rhscl-7-rpms  &&\
    yum install -y llvm-toolset-7 llvm-toolset-7-llvm-devel devtoolset-7-gcc*
RUN printf "source scl_source enable devtoolset-7\nsource scl_source enable llvm-toolset-7\n" > /usr/bin/scl_enable
ENV BASH_ENV=/usr/bin/scl_enable \
    ENV=/usr/bin/scl_enable \
    PROMPT_COMMAND=". /usr/bin/scl_enable"

RUN pip3 install numpy pandas bigfloat

RUN git clone https://github.com/verificarlo/verificarlo.git /opt/verificarlo/ &&\
    cd /opt/verificarlo/ &&\
    sed -i "s/print_information_header(ctx);/\/*print_information_header(ctx);*\//" src/backends/interflop-mca/interflop_mca.c &&\
    sed -i "s/if (!silent_load)/if (silent_load)/" src/vfcwrapper/main.c &&\
    ./autogen.sh &&\
    ./configure --without-flang --with-llvm=/opt/rh/llvm-toolset-7/root/usr/bin/ CC=/opt/rh/devtoolset-7/root/usr/bin/gcc CXX=/opt/rh/devtoolset-7/root/usr/bin/g++ &&\
    make &&\
    make install

# Install instrumented libmath
RUN git clone https://github.com/big-data-lab-team/MCA-libmath.git /opt/mca-libmath/ &&\
    (cd /opt/mca-libmath/ && make)


################### SPM ###################################

# Matlab (R2016b) installation 
# Instalation files are downloaded into matlab-install-R2016b
ADD matlab-install-R2016b /matlab-install/
ADD matlab_installer_input_R2016b.txt /matlab_installer_input.txt

RUN yum install -y libXtst libXtst-devel libXt libXt-devel \
                   libXrandr libXrandr-devel libGLU libGLU-devel
# Now install MATLAB (make sure that the install script is executable)
RUN cd /matlab-install && \
    chmod +x ./install && \
    ./install -mode silent \
        -inputFile /matlab_installer_input.txt \
        -outputFile /tmp/mlinstall.log \
        -destinationFolder /usr/local/MATLAB \
    ; EXIT=$? && cat /tmp/mlinstall.log && test $EXIT -eq 0

RUN cd /matlab-install &&\
    ./R2016b_Update_7_glnxa64.sh

RUN  ln -s /usr/local/MATLAB/bin/matlab /usr/local/bin/matlab
#ADD license_R2016b.lic /usr/local/MATLAB/licenses/license.lic

# Install SPM12 v7771 vs v6906
RUN  mkdir /opt/spm12 &&\
     curl -SL https://github.com/spm/spm12/archive/r6906.tar.gz \
     | tar -xzC /opt/spm12 --strip-components 1

ENV PATH=/usr/local/MATLAB/bin:$PATH
RUN cd /usr/local/bin &&\
    ln -s /usr/local/MATLAB/bin/mex
RUN cd /opt/spm12/src &&\
    make distclean &&\
    make && make install
